files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/nmusic_strings.xml
    translation: /app/src/main/res/values-%android_code%/nmusic_strings.xml
